# Generated by Django 5.2.12 on 2026-03-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContactoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, default='', max_length=40, verbose_name='teléfono')),
                ('resumen_confirmado', models.TextField(help_text='Texto que el cliente revisó antes de enviar.', verbose_name='resumen confirmado por el cliente')),
                ('historial_chat', models.JSONField(blank=True, default=list, help_text='Lista de turnos {rol, contenido} para contexto interno.', verbose_name='historial del chat (opcional)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
            ],
            options={
                'verbose_name': 'solicitud de contacto (chatbot)',
                'verbose_name_plural': 'solicitudes de contacto (chatbot)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
