# Generated by Django 5.2.12 on 2026-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_obra', models.CharField(max_length=150, verbose_name='Tipo de Obra')),
                ('medidas', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('presupuesto_estimado', models.CharField(max_length=100)),
                ('resumen_chatbot', models.TextField(blank=True, null=True)),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
    ]
