# Generated by Django 5.2.12 on 2026-03-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/excels/', verbose_name='Formato de Cotización (Excel)'),
        ),
    ]
