# Generated by Django 5.2.12 on 2026-03-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='ubicación')),
                ('url_imagen', models.URLField(help_text='Dirección pública de la foto representativa del proyecto.', max_length=500, verbose_name='URL de la imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-fecha_creacion', 'titulo'],
            },
        ),
    ]
