# Generated by Django 5.2.12 on 2026-03-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Tipo de obra para filtrar el catálogo (US-02).', max_length=120, verbose_name='categoría'),
        ),
    ]
