# Generated by Django 5.2.12 on 2026-03-25 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('medidas', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_cotizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('MANO_OBRA', 'Mano de Obra')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.FloatField()),
                ('unidad', models.CharField(max_length=50)),
                ('valor_unitario', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='FinanzasProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('utilidad_factor', models.CharField(blank=True, max_length=100, null=True)),
                ('utilidad_valor', models.FloatField()),
                ('total', models.FloatField()),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finanzas', to='projects.proyecto')),
            ],
        ),
    ]
