# Generated by Django 5.2.12 on 2026-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(default='Operario', max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
